from __future__ import annotations

from app.ai.state import AtlasState


class AtlasGraph:
    """Minimal graph orchestrator for the Atlas MVP conversation pipeline."""

    async def run(self, text: str) -> AtlasState:
        state = AtlasState(input_text=text)
        normalized = text.strip().lower()

        state.summary = f"Summary for: {text[:120]}"
        state.decisions = ["Need to act on the request"]
        state.action_items = [{"title": "Follow up", "status": "pending"}]
        state.risks = ["Risk captured from conversation"]
        state.questions = ["What would you like Atlas to do next?"]

        if "issue" in normalized or "ticket" in normalized:
            state.tool_name = "create_issue"
            state.tool_arguments = {
                "repo": "owner/repo",
                "title": text[:80].strip() or "Issue generated by Atlas",
                "body": text,
            }
            state.reply = "Planned action: create_issue"
        else:
            state.tool_name = None
            state.tool_arguments = {}
            state.reply = "Conversation understood."

        return state
