from __future__ import annotations

from app.ai.state import AtlasState


class Planner:
    """Plans the next action from the extracted conversation state."""

    def plan(self, state: AtlasState) -> AtlasState:
        if "issue" in state.input_text.lower() or "ticket" in state.input_text.lower():
            state.tool_name = "create_issue"
            state.tool_arguments = {
                "repo": "owner/repo",
                "title": state.input_text[:80].strip() or "Issue generated by Atlas",
                "body": state.input_text,
            }
        else:
            state.tool_name = None
            state.tool_arguments = {}
        return state
