export const PROVIDERS = [
  {
    id: "github",
    name: "GitHub",
    description: "Create and manage GitHub Issues directly from Slack threads.",
    icon: "🐙",
    iconBg: "rgba(36,41,47,0.8)",
    accentColor: "#f0f6ff",
    capabilities: ["create_issue", "search_issues"],
    phase: 1,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Receive summaries, notifications, and action items in Slack.",
    icon: "💬",
    iconBg: "rgba(78,26,103,0.6)",
    accentColor: "#e879f9",
    capabilities: ["send_message", "read_thread"],
    phase: 1,
  },
  {
    id: "jira",
    name: "Jira",
    description: "Auto-create Jira tickets from conversation summaries.",
    icon: "🎯",
    iconBg: "rgba(0,82,204,0.2)",
    accentColor: "#60a5fa",
    capabilities: ["create_issue", "update_issue"],
    phase: 2,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Generate and update Notion pages from engineering discussions.",
    icon: "📄",
    iconBg: "rgba(255,255,255,0.06)",
    accentColor: "#f0f6ff",
    capabilities: ["create_page", "update_page"],
    phase: 2,
  },
];
