"""Add provider_workspace_id to integrations

Revision ID: 450b499be824
Revises: 0003_enterprise_identity
Create Date: 2026-08-07 10:08:52.577977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450b499be824'
down_revision: Union[str, Sequence[str], None] = '0003_enterprise_identity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_active'), table_name='api_keys', postgresql_where='(is_active = true)')
    op.drop_constraint(op.f('api_keys_created_by_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'service_accounts', ['service_account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_keys', 'created_by_user_id')
    op.add_column('integrations', sa.Column('provider_workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_integrations_provider_workspace_id'), 'integrations', ['provider_workspace_id'], unique=False)
    op.alter_column('oauth_accounts', 'encrypted_access_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'encrypted_refresh_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('oauth_accounts', 'encrypted_refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'encrypted_access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_integrations_provider_workspace_id'), table_name='integrations')
    op.drop_column('integrations', 'provider_workspace_id')
    op.add_column('api_keys', sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_created_by_user_id_fkey'), 'api_keys', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_api_keys_active'), 'api_keys', ['workspace_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
