"""add integration user permissions

Revision ID: 7be135ca3304
Revises: bac9673daa5f
Create Date: 2026-08-08 09:18:38.542196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7be135ca3304'
down_revision: Union[str, Sequence[str], None] = 'bac9673daa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('integration_users', sa.Column('can_read', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('integration_users', sa.Column('can_write', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('integration_users', sa.Column('can_delete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('integration_users', sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_users', 'raw_profile')
    op.drop_column('integration_users', 'can_delete')
    op.drop_column('integration_users', 'can_write')
    op.drop_column('integration_users', 'can_read')
    op.drop_column('integration_users', 'is_active')
    # ### end Alembic commands ###
